title: Mahdi Nasseri
logo: /assets/img/headshot.jpeg
description: >
  <h4>Strategic Data & Insights Leader | Analytics Team Builder</h4>
  📧 <a href='mailto:mahdi.nasseri@gmail.com' target="_blank">mahdi.nasseri@gmail.com</a>
  <br>
  🔗 <a href='https://linkedin.com/in/mahdinasseri' target="_blank">LinkedIn</a></br>
  💻 <a href='https://github.com/mahdinasseri' target="_blank">GitHub</a></br>
  📝 <a href='https://medium.com/@mahdinasseri' target="_blank">Medium Blog</a>
show_downloads: false
theme: jekyll-theme-minimal
