title: Mahdi Nasseri
logo: /assets/img/headshot.jpeg
description: 
<h1>Strategic Data & Insights Leader | Analytics Team Builder</h1>
<h2>| 🧠 Data Storyteller | 📊 Analytics Strategist</h2>
<br>
📧 mahdi.nasseri@gmail.com    🔗 <a href='https://linkedin.com/in/mahdinasseri'>LinkedIn</a>
<br>
Seasoned <b>Data & Insights Manager</b> with over 10 years of experience leading <b>data strategy, business intelligence</b>, and analytics functions in high-growth tech companies. Expert in <b>transforming business challenges into data-informed strategies</b>, building high-performing data teams, and developing robust analytics infrastructure. Proven success across e-commerce, app marketplaces, and classified platforms through <b>predictive analytics, reporting automation</b>, and user behavior modeling. Fluent in SQL, Python, PySpark, and visualization tools like Power BI and Metabase.
show_downloads: false
theme: jekyll-theme-minimal
