title: Mahdi Nasseri
logo: /assets/img/headshot.jpeg
description: >
  <h4>Strategic Data & Insights Leader | Analytics Team Builder</h4>
  📧 mahdi.nasseri@gmail.com
  <br>
  🔗 <a href='https://linkedin.com/in/mahdinasseri'>LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
